# Generated by Django 6.0.2 on 2026-05-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_barangay_code_userprofile_city_code_and_more'),
        ('api', '0002_userprofile_full_name'),
    ]

    operations = [
    ]
