# Generated by Django 6.0.4 on 2026-05-29 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_20260528_1852'),
        ('api', '0003_merge_20260529_0012'),
    ]

    operations = [
    ]
